// <auto-generated />
using GrupoMad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrupoMad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251028054638_CreateStore")]
    partial class CreateStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GrupoMad.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Deconolux"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Persianas Mad"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Persitex"
                        });
                });

            modelBuilder.Entity("GrupoMad.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Name = "Sucursal Pachuca Revolucion"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Name = "Sucursal Pachuca Plaza de las Americas"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            Name = "Sucursal Puebla"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            Name = "Sucursal Tlaxcala"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            Name = "Sucursal Apizaco"
                        });
                });

            modelBuilder.Entity("GrupoMad.Models.Store", b =>
                {
                    b.HasOne("GrupoMad.Models.Company", "Company")
                        .WithMany("Stores")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GrupoMad.Models.Company", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
